### ISSUE TITLE
can not work in windows

### ISSUE THREAD

**Issue by newer-android** [point-source/dart_ping#29]
when use it on windows,it report [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: FormatException: Invalid UTF-8 byte (at offset 0)
how can i resove it

**Comment by point-source** [comment]
What is the default language on your windows installation?

**Comment by newer-android** [comment]
CHINESE

**Comment by newer-android** [comment]
i do not set language,

**Comment by point-source** [comment]
Since this library parses the output from the terminal/cmd, it requires either the output to be in English or for the user to provide a custom parser as documented:

<img width="799" alt="Screen Shot 2022-08-15 at 1 45 56 AM" src="https://user-images.githubusercontent.com/47544779/184604883-4264a4f8-c4ae-413a-a0c5-09620bce9471.png">

**Comment by YowFung** [comment]
@newer-android 
兄弟，你的问题解决了吗，我遇到了一个跟你类似的问题。但它并不是一直都会报下面的错误，只在部分电脑上会出现问题（都是 Windows 10 系统）。
```log
ERROR: FormatException: Missing extension byte (at offset 3)
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1859)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111)
#5      _rootRunUnary (dart:async/zone.dart:1399)
#6      _CustomZone.runUnary (dart:async/zone.dart:1300)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774)
#11     _StreamController._add (dart:async/stream_controller.dart:648)
#12     _StreamController.add (dart:async/stream_controller.dart:596)
#13     _rootRunUnary (dart:async/zone.dart:1399)
#14     _CustomZone.runUnary (dart:async/zone.dart:1300)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#18     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774)
#19     _StreamController._add (dart:async/stream_controller.dart:648)
#20     _StreamController.add (dart:async/stream_controller.dart:596)
#21     _Socket._onData (dart:io-patch/socket_patch.dart:2324)
#22     _rootRunUnary (dart:async/zone.dart:1407)
#23     _CustomZone.runUnary (dart:async/zone.dart:1300)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#27     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774)
#28     _StreamController._add (dart:async/stream_controller.dart:648)
#29     _StreamController.add (dart:async/stream_controller.dart:596)
#30     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1849)
#31     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
```

**Comment by point-source** [comment]
Closing due to inactivity.
