### ISSUE TITLE
Windows11 throw FormatException: Unexpected extension byte (at offset 29)

### ISSUE THREAD

**Issue by RikitoNoto** [point-source/dart_ping#51]
Hello.
Thank you to create this great package.
I like this package and often use.

One day, i use this package on Windows 11, thrown a exception.
```bash
Unhandled exception:
FormatException: Unexpected extension byte (at offset 29)
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1851:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:304:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#9      _StreamController._add (dart:async/stream_controller.dart:650:7)
#10     _StreamController.add (dart:async/stream_controller.dart:598:5)
#11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#15     _StreamController._add (dart:async/stream_controller.dart:650:7)
#16     _StreamController.add (dart:async/stream_controller.dart:598:5)
#17     _Socket._onData (dart:io-patch/socket_patch.dart:2381:41)
#18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#21     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#22     _StreamController._add (dart:async/stream_controller.dart:650:7)
#23     _StreamController.add (dart:async/stream_controller.dart:598:5)
#24     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1899:33)
#25     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1356:14)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#29     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190:5)
```

I investigated about this exception, but i didn't know why it occur.

**Comment by point-source** [comment]
What is the default language of the OS?

**Comment by RikitoNoto** [comment]
My default language is Japanese.

**Comment by Ampy** [comment]
1.引入 import 'package:fast_gbk/fast_gbk.dart';
2.添加代码：
  final parser = PingParser(
      responseStr: RegExp(r'来自'),
      responseRgx: RegExp(
          r'来自 (?<ip>.*)的回复: 字节=(?:\d+) 时间=(?<time>\d+)ms TTL=(?<ttl>\d+)'),
      summaryStr: RegExp(r'丢失'),
      summaryRgx: RegExp(r'已发送 = (?<tx>\d+)，已接收 = (?<rx>\d+)，丢失 = (?:\d+)'),
      timeoutStr: RegExp(r'请求超时'),
      unknownHostStr: RegExp(r'请求找不到主机'));
3.调用地方这样写：
     Ping('baidu.com',count: 5,parser: parser,encoding: const GbkCodec(allowMalformed: true));

**Comment by point-source** [comment]
This should now be fixed through the use of the `forceCodepage` flag on version [9.0.0](https://pub.dev/packages/dart_ping/versions/9.0.0). Please reopen if this does not solve it for you:

```dart
final ping = Ping('google.com', forceCodepage: true);
```

**Comment by RikitoNoto** [comment]
@point-source 
Thank you, I was able run without any exception!
