### ISSUE TITLE
Ping on relase

### ISSUE THREAD

**Issue by MarcuzziGiuseppe** [point-source/dart_ping#59]
I've tryed to do a ping and compile my app in release mode using this code:

```
final result = await Ping(ipServer, count: 1).stream.first;
    if (result.error != null || result.response == null) {
      return false;
    } else if (result.response != null || result.error == null) {
      return true;
    }
```

but it return this error:
E/flutter (14799): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
E/flutter (14799): #0      Stream.first.<anonymous closure> (dart:async/stream.dart:1575)
E/flutter (14799): #1      _RootZone.runGuarded (dart:async/zone.dart:1582)
E/flutter (14799): #2      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392)
E/flutter (14799): #3      _RootZone.run (dart:async/zone.dart:1655)
E/flutter (14799): #4      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:199)
E/flutter (14799): #5      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:810)
E/flutter (14799): #6      Future._propagateToListeners (dart:async/future_impl.dart:866)
E/flutter (14799): #7      Future._prependListeners.<anonymous closure> (dart:async/future_impl.dart:492)
E/flutter (14799): #8      _microtaskLoop (dart:async/schedule_microtask.dart:40)
E/flutter (14799): #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

anyway if i cmpile and run in debug mode it works perfectly

this app run on an android device

**Comment by MarcuzziGiuseppe** [comment]
This is developed for an android device

**Comment by khanems** [comment]
final result = await Ping(ipServer, count: 1).stream.first;
if (result.error != null || result.response == null) {
  return false;
} else {
  return true;
}

**Comment by point-source** [comment]
now that [v10.0.0](https://github.com/point-source/dart_ping/tree/v10.0.0) ([pub.dev](https://pub.dev/packages/dart_ping/versions/10.0.0)) is out and includes a significant refactor, I am closing this until it comes up again. I have not been able to reproduce on the latest version.
